### ISSUE TITLE
Include minified and production-ready release

### ISSUE THREAD

**Issue by dariye** [akinjide/is#4]
It would be great to have a minified version of this lib in a `dist` dir and npm.

**Comment by akinjide** [comment]
`index.js` `line 3` contains instructions to minify before deployment.

**Comment by dariye** [comment]
As this is a utility lib, seems only proper to have a readily available production-ready version. From a user perspective, seems like a hassle to clone then minify. In that time, I could just write a few functions in my already-configured environment.

**Comment by akinjide** [comment]
[commit 24](https://github.com/akinjide/is/commit/c10de772cefb38baab6e55f6406a6f3085c0fac1) resolves issue
